"""add role and password hash to users

Revision ID: 226e5b05f170
Revises: b7cd9d1a1fd3
Create Date: 2026-08-29 11:59:40.560790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226e5b05f170'
down_revision: Union[str, Sequence[str], None] = 'b7cd9d1a1fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum('admin', 'manager', 'user', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role', role_enum, nullable=False))
    op.alter_column('users', 'create_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'create_at_shamsi',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'create_at_shamsi',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'create_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    role_enum = sa.Enum('admin', 'manager', 'user', name='role')
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
